# Development and Test environment configurations are listed here
# for convenience but generally shouldn't be used.
#
# Replace YOUR_APP with the heroku app name and YOUR_TOKEN with the
# same token used in private_pub.yml of your rails project.

production:
  server: "http://idserver.herokuapp.com/faye"
  secret_token: "f5efbaa1e44c3729885681f8d6c6cb8987b96534033fa5f518fbba6bbef76987"
  signature_expiration: 86400 # one day
